//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protocols/csmj_protocol.proto
namespace KWX
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_HeartBeat")]
  public partial class CMD_HeartBeat : global::ProtoBuf.IExtensible
  {
    public CMD_HeartBeat() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RSP_HeartBeat")]
  public partial class RSP_HeartBeat : global::ProtoBuf.IExtensible
  {
    public RSP_HeartBeat() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_LoginServer")]
  public partial class CMD_LoginServer : global::ProtoBuf.IExtensible
  {
    public CMD_LoginServer() {}
    
    private string _Password = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private uint _RoomID = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"RoomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint RoomID
    {
      get { return _RoomID; }
      set { _RoomID = value; }
    }
    private uint _SeatID = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"SeatID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint SeatID
    {
      get { return _SeatID; }
      set { _SeatID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RSP_LoginServer")]
  public partial class RSP_LoginServer : global::ProtoBuf.IExtensible
  {
    public RSP_LoginServer() {}
    
    private int _Error = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Error", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Error
    {
      get { return _Error; }
      set { _Error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_ExitRoom")]
  public partial class CMD_ExitRoom : global::ProtoBuf.IExtensible
  {
    public CMD_ExitRoom() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RSP_ExitRoom")]
  public partial class RSP_ExitRoom : global::ProtoBuf.IExtensible
  {
    public RSP_ExitRoom() {}
    
    private int _Error = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Error", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Error
    {
      get { return _Error; }
      set { _Error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_Message")]
  public partial class CMD_Message : global::ProtoBuf.IExtensible
  {
    public CMD_Message() {}
    
    private string _Message = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Message
    {
      get { return _Message; }
      set { _Message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_QueryData")]
  public partial class CMD_QueryData : global::ProtoBuf.IExtensible
  {
    public CMD_QueryData() {}
    
    private string _Password = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private ulong _QueryID = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"QueryID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong QueryID
    {
      get { return _QueryID; }
      set { _QueryID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RSP_QueryData")]
  public partial class RSP_QueryData : global::ProtoBuf.IExtensible
  {
    public RSP_QueryData() {}
    
    private int _Error = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Error", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Error
    {
      get { return _Error; }
      set { _Error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_Dismiss")]
  public partial class CMD_Dismiss : global::ProtoBuf.IExtensible
  {
    public CMD_Dismiss() {}
    
    private int _Action = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Action
    {
      get { return _Action; }
      set { _Action = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NTF_RoomUserInfo")]
  public partial class NTF_RoomUserInfo : global::ProtoBuf.IExtensible
  {
    public NTF_RoomUserInfo() {}
    
    private uint _SeatID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SeatID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint SeatID
    {
      get { return _SeatID; }
      set { _SeatID = value; }
    }
    private ulong _UserID = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"UserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong UserID
    {
      get { return _UserID; }
      set { _UserID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NTF_SameUserLogin")]
  public partial class NTF_SameUserLogin : global::ProtoBuf.IExtensible
  {
    public NTF_SameUserLogin() {}
    
    private uint _IP = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"IP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint IP
    {
      get { return _IP; }
      set { _IP = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NTF_RoomUserOnline")]
  public partial class NTF_RoomUserOnline : global::ProtoBuf.IExtensible
  {
    public NTF_RoomUserOnline() {}
    
    private uint _SeatID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SeatID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint SeatID
    {
      get { return _SeatID; }
      set { _SeatID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NTF_RoomUserOffline")]
  public partial class NTF_RoomUserOffline : global::ProtoBuf.IExtensible
  {
    public NTF_RoomUserOffline() {}
    
    private uint _SeatID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SeatID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint SeatID
    {
      get { return _SeatID; }
      set { _SeatID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NTF_RoomDismissed")]
  public partial class NTF_RoomDismissed : global::ProtoBuf.IExtensible
  {
    public NTF_RoomDismissed() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NTF_Message")]
  public partial class NTF_Message : global::ProtoBuf.IExtensible
  {
    public NTF_Message() {}
    
    private uint _SeatID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SeatID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint SeatID
    {
      get { return _SeatID; }
      set { _SeatID = value; }
    }
    private string _Message = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Message
    {
      get { return _Message; }
      set { _Message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NTF_Dismiss")]
  public partial class NTF_Dismiss : global::ProtoBuf.IExtensible
  {
    public NTF_Dismiss() {}
    
    private readonly global::System.Collections.Generic.List<int> _Action = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> Action
    {
      get { return _Action; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PB_Client_DealCard")]
  public partial class PB_Client_DealCard : global::ProtoBuf.IExtensible
  {
    public PB_Client_DealCard() {}
    
    private uint _card_value = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"card_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint card_value
    {
      get { return _card_value; }
      set { _card_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PB_Client_ChiCard")]
  public partial class PB_Client_ChiCard : global::ProtoBuf.IExtensible
  {
    public PB_Client_ChiCard() {}
    
    private readonly global::System.Collections.Generic.List<uint> _chi_card = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"chi_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> chi_card
    {
      get { return _chi_card; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PB_Client_PengCard")]
  public partial class PB_Client_PengCard : global::ProtoBuf.IExtensible
  {
    public PB_Client_PengCard() {}
    
    private uint _peng_card = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"peng_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint peng_card
    {
      get { return _peng_card; }
      set { _peng_card = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PB_Client_GangCard")]
  public partial class PB_Client_GangCard : global::ProtoBuf.IExtensible
  {
    public PB_Client_GangCard() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PB_Client_KaiGang")]
  public partial class PB_Client_KaiGang : global::ProtoBuf.IExtensible
  {
    public PB_Client_KaiGang() {}
    
    private uint _gang_card = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gang_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gang_card
    {
      get { return _gang_card; }
      set { _gang_card = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PB_Client_BuZhang")]
  public partial class PB_Client_BuZhang : global::ProtoBuf.IExtensible
  {
    public PB_Client_BuZhang() {}
    
    private uint _gang_card = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gang_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gang_card
    {
      get { return _gang_card; }
      set { _gang_card = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PB_Client_HuPai")]
  public partial class PB_Client_HuPai : global::ProtoBuf.IExtensible
  {
    public PB_Client_HuPai() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PB_Client_Pass")]
  public partial class PB_Client_Pass : global::ProtoBuf.IExtensible
  {
    public PB_Client_Pass() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PB_Client_HDP")]
  public partial class PB_Client_HDP : global::ProtoBuf.IExtensible
  {
    public PB_Client_HDP() {}
    
    private uint _want = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"want", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint want
    {
      get { return _want; }
      set { _want = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PB_Client_Player_Ready")]
  public partial class PB_Client_Player_Ready : global::ProtoBuf.IExtensible
  {
    public PB_Client_Player_Ready() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PB_Server_Player_Info")]
  public partial class PB_Server_Player_Info : global::ProtoBuf.IExtensible
  {
    public PB_Server_Player_Info() {}
    
    private uint _seat_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"seat_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint seat_id
    {
      get { return _seat_id; }
      set { _seat_id = value; }
    }
    private int _player_status = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"player_status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int player_status
    {
      get { return _player_status; }
      set { _player_status = value; }
    }
    private uint _ting_pai = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ting_pai", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ting_pai
    {
      get { return _ting_pai; }
      set { _ting_pai = value; }
    }
    private uint _zha_niao = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"zha_niao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint zha_niao
    {
      get { return _zha_niao; }
      set { _zha_niao = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _can_chi_card = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"can_chi_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> can_chi_card
    {
      get { return _can_chi_card; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _can_peng_card = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"can_peng_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> can_peng_card
    {
      get { return _can_peng_card; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _can_gang_card = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(7, Name=@"can_gang_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> can_gang_card
    {
      get { return _can_gang_card; }
    }
  
    private uint _hu_pai_type = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"hu_pai_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint hu_pai_type
    {
      get { return _hu_pai_type; }
      set { _hu_pai_type = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _have_chi_card = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(9, Name=@"have_chi_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> have_chi_card
    {
      get { return _have_chi_card; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _have_peng_card = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(10, Name=@"have_peng_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> have_peng_card
    {
      get { return _have_peng_card; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _have_gang_card = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(11, Name=@"have_gang_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> have_gang_card
    {
      get { return _have_gang_card; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _last_cards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(12, Name=@"last_cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> last_cards
    {
      get { return _last_cards; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _play_cards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(13, Name=@"play_cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> play_cards
    {
      get { return _play_cards; }
    }
  
    private uint _action = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint action
    {
      get { return _action; }
      set { _action = value; }
    }
    private uint _cards = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cards
    {
      get { return _cards; }
      set { _cards = value; }
    }
    private int _player_score = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"player_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int player_score
    {
      get { return _player_score; }
      set { _player_score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PB_Server_Room_Info")]
  public partial class PB_Server_Room_Info : global::ProtoBuf.IExtensible
  {
    public PB_Server_Room_Info() {}
    
    private int _nReturnCode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"nReturnCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nReturnCode
    {
      get { return _nReturnCode; }
      set { _nReturnCode = value; }
    }
    private readonly global::System.Collections.Generic.List<PB_Server_Player_Info> _player_info = new global::System.Collections.Generic.List<PB_Server_Player_Info>();
    [global::ProtoBuf.ProtoMember(2, Name=@"player_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PB_Server_Player_Info> player_info
    {
      get { return _player_info; }
    }
  
    private uint _banker = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"banker", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint banker
    {
      get { return _banker; }
      set { _banker = value; }
    }
    private uint _next = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"next", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint next
    {
      get { return _next; }
      set { _next = value; }
    }
    private uint _opposite = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"opposite", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint opposite
    {
      get { return _opposite; }
      set { _opposite = value; }
    }
    private uint _top = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"top", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint top
    {
      get { return _top; }
      set { _top = value; }
    }
    private uint _last_player = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"last_player", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint last_player
    {
      get { return _last_player; }
      set { _last_player = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _turn_player = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(8, Name=@"turn_player", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> turn_player
    {
      get { return _turn_player; }
    }
  
    private uint _round_num = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"round_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint round_num
    {
      get { return _round_num; }
      set { _round_num = value; }
    }
    private uint _max_round = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"max_round", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint max_round
    {
      get { return _max_round; }
      set { _max_round = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _dice = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(11, Name=@"dice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> dice
    {
      get { return _dice; }
    }
  
    private uint _room_status = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"room_status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint room_status
    {
      get { return _room_status; }
      set { _room_status = value; }
    }
    private uint _mo_card = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"mo_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mo_card
    {
      get { return _mo_card; }
      set { _mo_card = value; }
    }
    private uint _last_cards_size = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"last_cards_size", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint last_cards_size
    {
      get { return _last_cards_size; }
      set { _last_cards_size = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _last_deal_card = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(15, Name=@"last_deal_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> last_deal_card
    {
      get { return _last_deal_card; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _win_player = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(16, Name=@"win_player", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> win_player
    {
      get { return _win_player; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PB_Server_Single_Player")]
  public partial class PB_Server_Single_Player : global::ProtoBuf.IExtensible
  {
    public PB_Server_Single_Player() {}
    
    private uint _seat_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"seat_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint seat_id
    {
      get { return _seat_id; }
      set { _seat_id = value; }
    }
    private int _score = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private int _hu_pai_type = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"hu_pai_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hu_pai_type
    {
      get { return _hu_pai_type; }
      set { _hu_pai_type = value; }
    }
    private uint _hu_pai = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"hu_pai", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint hu_pai
    {
      get { return _hu_pai; }
      set { _hu_pai = value; }
    }
    private int _hu_pai_type1 = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"hu_pai_type1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hu_pai_type1
    {
      get { return _hu_pai_type1; }
      set { _hu_pai_type1 = value; }
    }
    private uint _hu_pai1 = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"hu_pai1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint hu_pai1
    {
      get { return _hu_pai1; }
      set { _hu_pai1 = value; }
    }
    private uint _hu_pai_style = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"hu_pai_style", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint hu_pai_style
    {
      get { return _hu_pai_style; }
      set { _hu_pai_style = value; }
    }
    private uint _zhong_niao_count = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"zhong_niao_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint zhong_niao_count
    {
      get { return _zhong_niao_count; }
      set { _zhong_niao_count = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _last_cards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(9, Name=@"last_cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> last_cards
    {
      get { return _last_cards; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _have_chi_card = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(10, Name=@"have_chi_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> have_chi_card
    {
      get { return _have_chi_card; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _have_peng_card = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(11, Name=@"have_peng_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> have_peng_card
    {
      get { return _have_peng_card; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _have_gang_card = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(12, Name=@"have_gang_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> have_gang_card
    {
      get { return _have_gang_card; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PB_Server_Single_Bill")]
  public partial class PB_Server_Single_Bill : global::ProtoBuf.IExtensible
  {
    public PB_Server_Single_Bill() {}
    
    private uint _round_num = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"round_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint round_num
    {
      get { return _round_num; }
      set { _round_num = value; }
    }
    private uint _max_round = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"max_round", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint max_round
    {
      get { return _max_round; }
      set { _max_round = value; }
    }
    private uint _title = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint title
    {
      get { return _title; }
      set { _title = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _zhong_niao_pai = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(4, Name=@"zhong_niao_pai", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> zhong_niao_pai
    {
      get { return _zhong_niao_pai; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _hu_pai_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"hu_pai_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> hu_pai_id
    {
      get { return _hu_pai_id; }
    }
  
    private readonly global::System.Collections.Generic.List<PB_Server_Single_Player> _player_info = new global::System.Collections.Generic.List<PB_Server_Single_Player>();
    [global::ProtoBuf.ProtoMember(6, Name=@"player_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PB_Server_Single_Player> player_info
    {
      get { return _player_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PB_Server_All_Player_Info")]
  public partial class PB_Server_All_Player_Info : global::ProtoBuf.IExtensible
  {
    public PB_Server_All_Player_Info() {}
    
    private uint _seat_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"seat_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint seat_id
    {
      get { return _seat_id; }
      set { _seat_id = value; }
    }
    private uint _win = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"win", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint win
    {
      get { return _win; }
      set { _win = value; }
    }
    private uint _fang_pao = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"fang_pao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fang_pao
    {
      get { return _fang_pao; }
      set { _fang_pao = value; }
    }
    private uint _get_pao = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"get_pao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint get_pao
    {
      get { return _get_pao; }
      set { _get_pao = value; }
    }
    private uint _zi_mo = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"zi_mo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint zi_mo
    {
      get { return _zi_mo; }
      set { _zi_mo = value; }
    }
    private uint _kai_gang = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"kai_gang", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint kai_gang
    {
      get { return _kai_gang; }
      set { _kai_gang = value; }
    }
    private uint _zha_niao = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"zha_niao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint zha_niao
    {
      get { return _zha_niao; }
      set { _zha_niao = value; }
    }
    private int _all_score = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"all_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int all_score
    {
      get { return _all_score; }
      set { _all_score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PB_Server_ALL_Bill_Info")]
  public partial class PB_Server_ALL_Bill_Info : global::ProtoBuf.IExtensible
  {
    public PB_Server_ALL_Bill_Info() {}
    
    private readonly global::System.Collections.Generic.List<PB_Server_All_Player_Info> _player_info = new global::System.Collections.Generic.List<PB_Server_All_Player_Info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"player_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PB_Server_All_Player_Info> player_info
    {
      get { return _player_info; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _best_win = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"best_win", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> best_win
    {
      get { return _best_win; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _best_pao = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"best_pao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> best_pao
    {
      get { return _best_pao; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}