//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protocols/Game.proto
namespace KWX
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_HeartBeat")]
  public partial class CMD_HeartBeat : global::ProtoBuf.IExtensible
  {
    public CMD_HeartBeat() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RSP_HeartBeat")]
  public partial class RSP_HeartBeat : global::ProtoBuf.IExtensible
  {
    public RSP_HeartBeat() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_LoginServer")]
  public partial class CMD_LoginServer : global::ProtoBuf.IExtensible
  {
    public CMD_LoginServer() {}
    
    private string _Password = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private uint _RoomID = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"RoomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint RoomID
    {
      get { return _RoomID; }
      set { _RoomID = value; }
    }
    private uint _SeatID = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"SeatID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint SeatID
    {
      get { return _SeatID; }
      set { _SeatID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RSP_LoginServer")]
  public partial class RSP_LoginServer : global::ProtoBuf.IExtensible
  {
    public RSP_LoginServer() {}
    
    private int _Error = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Error", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Error
    {
      get { return _Error; }
      set { _Error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_ExitRoom")]
  public partial class CMD_ExitRoom : global::ProtoBuf.IExtensible
  {
    public CMD_ExitRoom() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RSP_ExitRoom")]
  public partial class RSP_ExitRoom : global::ProtoBuf.IExtensible
  {
    public RSP_ExitRoom() {}
    
    private int _Error = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Error", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Error
    {
      get { return _Error; }
      set { _Error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_Message")]
  public partial class CMD_Message : global::ProtoBuf.IExtensible
  {
    public CMD_Message() {}
    
    private string _Message = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Message
    {
      get { return _Message; }
      set { _Message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_QueryData")]
  public partial class CMD_QueryData : global::ProtoBuf.IExtensible
  {
    public CMD_QueryData() {}
    
    private string _Password = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private ulong _QueryID = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"QueryID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong QueryID
    {
      get { return _QueryID; }
      set { _QueryID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RSP_QueryData")]
  public partial class RSP_QueryData : global::ProtoBuf.IExtensible
  {
    public RSP_QueryData() {}
    
    private int _Error = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Error", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Error
    {
      get { return _Error; }
      set { _Error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NTF_RoomUserInfo")]
  public partial class NTF_RoomUserInfo : global::ProtoBuf.IExtensible
  {
    public NTF_RoomUserInfo() {}
    
    private uint _SeatID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SeatID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint SeatID
    {
      get { return _SeatID; }
      set { _SeatID = value; }
    }
    private ulong _UserID = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"UserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong UserID
    {
      get { return _UserID; }
      set { _UserID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NTF_SameUserLogin")]
  public partial class NTF_SameUserLogin : global::ProtoBuf.IExtensible
  {
    public NTF_SameUserLogin() {}
    
    private uint _IP = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"IP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint IP
    {
      get { return _IP; }
      set { _IP = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NTF_RoomUserOnline")]
  public partial class NTF_RoomUserOnline : global::ProtoBuf.IExtensible
  {
    public NTF_RoomUserOnline() {}
    
    private uint _SeatID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SeatID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint SeatID
    {
      get { return _SeatID; }
      set { _SeatID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NTF_RoomUserOffline")]
  public partial class NTF_RoomUserOffline : global::ProtoBuf.IExtensible
  {
    public NTF_RoomUserOffline() {}
    
    private uint _SeatID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SeatID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint SeatID
    {
      get { return _SeatID; }
      set { _SeatID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NTF_RoomDismissed")]
  public partial class NTF_RoomDismissed : global::ProtoBuf.IExtensible
  {
    public NTF_RoomDismissed() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NTF_Message")]
  public partial class NTF_Message : global::ProtoBuf.IExtensible
  {
    public NTF_Message() {}
    
    private uint _SeatID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SeatID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint SeatID
    {
      get { return _SeatID; }
      set { _SeatID = value; }
    }
    private string _Message = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Message
    {
      get { return _Message; }
      set { _Message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ACTION_CHUPAI")]
  public partial class ACTION_CHUPAI : global::ProtoBuf.IExtensible
  {
    public ACTION_CHUPAI() {}
    
    private int _Pai = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Pai", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Pai
    {
      get { return _Pai; }
      set { _Pai = value; }
    }
    private bool _Ting = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Ting", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Ting
    {
      get { return _Ting; }
      set { _Ting = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _BuLiang = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"BuLiang", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> BuLiang
    {
      get { return _BuLiang; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ACTION_CHI")]
  public partial class ACTION_CHI : global::ProtoBuf.IExtensible
  {
    public ACTION_CHI() {}
    
    private int _Pai = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Pai", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Pai
    {
      get { return _Pai; }
      set { _Pai = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ACTION_PENG")]
  public partial class ACTION_PENG : global::ProtoBuf.IExtensible
  {
    public ACTION_PENG() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ACTION_GANG")]
  public partial class ACTION_GANG : global::ProtoBuf.IExtensible
  {
    public ACTION_GANG() {}
    
    private int _Pai = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Pai", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Pai
    {
      get { return _Pai; }
      set { _Pai = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ACTION_HU")]
  public partial class ACTION_HU : global::ProtoBuf.IExtensible
  {
    public ACTION_HU() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ACTION_GUO")]
  public partial class ACTION_GUO : global::ProtoBuf.IExtensible
  {
    public ACTION_GUO() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ACTION_RESTART")]
  public partial class ACTION_RESTART : global::ProtoBuf.IExtensible
  {
    public ACTION_RESTART() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SHOUZHANG")]
  public partial class SHOUZHANG : global::ProtoBuf.IExtensible
  {
    public SHOUZHANG() {}
    
    private int _Pai = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Pai", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Pai
    {
      get { return _Pai; }
      set { _Pai = value; }
    }
    private int _State = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"State", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int State
    {
      get { return _State; }
      set { _State = value; }
    }
    private bool _Gray = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Gray", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Gray
    {
      get { return _Gray; }
      set { _Gray = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KAN")]
  public partial class KAN : global::ProtoBuf.IExtensible
  {
    public KAN() {}
    
    private bool _AnGang = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"AnGang", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool AnGang
    {
      get { return _AnGang; }
      set { _AnGang = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _Pai = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"Pai", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> Pai
    {
      get { return _Pai; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PLAYER_STATE")]
  public partial class PLAYER_STATE : global::ProtoBuf.IExtensible
  {
    public PLAYER_STATE() {}
    
    private readonly global::System.Collections.Generic.List<SHOUZHANG> _ShouZhang = new global::System.Collections.Generic.List<SHOUZHANG>();
    [global::ProtoBuf.ProtoMember(1, Name=@"ShouZhang", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SHOUZHANG> ShouZhang
    {
      get { return _ShouZhang; }
    }
  
    private readonly global::System.Collections.Generic.List<KAN> _XiaZhang = new global::System.Collections.Generic.List<KAN>();
    [global::ProtoBuf.ProtoMember(2, Name=@"XiaZhang", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<KAN> XiaZhang
    {
      get { return _XiaZhang; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _QiZhang = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"QiZhang", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> QiZhang
    {
      get { return _QiZhang; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _YiTing = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"YiTing", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> YiTing
    {
      get { return _YiTing; }
    }
  
    private bool _ChuPai = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"ChuPai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool ChuPai
    {
      get { return _ChuPai; }
      set { _ChuPai = value; }
    }
    private int _BeiShu = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"BeiShu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int BeiShu
    {
      get { return _BeiShu; }
      set { _BeiShu = value; }
    }
    private int _GangFen = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"GangFen", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int GangFen
    {
      get { return _GangFen; }
      set { _GangFen = value; }
    }
    private uint _HuPaiCiShu = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"HuPaiCiShu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint HuPaiCiShu
    {
      get { return _HuPaiCiShu; }
      set { _HuPaiCiShu = value; }
    }
    private uint _ZiMoCiShu = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"ZiMoCiShu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ZiMoCiShu
    {
      get { return _ZiMoCiShu; }
      set { _ZiMoCiShu = value; }
    }
    private uint _ZuiDaBeiShu = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"ZuiDaBeiShu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ZuiDaBeiShu
    {
      get { return _ZuiDaBeiShu; }
      set { _ZuiDaBeiShu = value; }
    }
    private uint _GangPaiCiShu = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"GangPaiCiShu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint GangPaiCiShu
    {
      get { return _GangPaiCiShu; }
      set { _GangPaiCiShu = value; }
    }
    private uint _LiangDaoCiShu = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"LiangDaoCiShu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint LiangDaoCiShu
    {
      get { return _LiangDaoCiShu; }
      set { _LiangDaoCiShu = value; }
    }
    private uint _DiaoPaoCiShu = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"DiaoPaoCiShu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint DiaoPaoCiShu
    {
      get { return _DiaoPaoCiShu; }
      set { _DiaoPaoCiShu = value; }
    }
    private int _Action = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"Action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Action
    {
      get { return _Action; }
      set { _Action = value; }
    }
    private bool _PengPengHu = default(bool);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"PengPengHu", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool PengPengHu
    {
      get { return _PengPengHu; }
      set { _PengPengHu = value; }
    }
    private bool _QiDui = default(bool);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"QiDui", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool QiDui
    {
      get { return _QiDui; }
      set { _QiDui = value; }
    }
    private bool _ZiMoHu = default(bool);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"ZiMoHu", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool ZiMoHu
    {
      get { return _ZiMoHu; }
      set { _ZiMoHu = value; }
    }
    private bool _MingSiGuiYi = default(bool);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"MingSiGuiYi", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool MingSiGuiYi
    {
      get { return _MingSiGuiYi; }
      set { _MingSiGuiYi = value; }
    }
    private bool _AnSiGuiYi = default(bool);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"AnSiGuiYi", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool AnSiGuiYi
    {
      get { return _AnSiGuiYi; }
      set { _AnSiGuiYi = value; }
    }
    private bool _LongQiDui = default(bool);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"LongQiDui", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool LongQiDui
    {
      get { return _LongQiDui; }
      set { _LongQiDui = value; }
    }
    private bool _ShuangLongQiDui = default(bool);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"ShuangLongQiDui", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool ShuangLongQiDui
    {
      get { return _ShuangLongQiDui; }
      set { _ShuangLongQiDui = value; }
    }
    private bool _DaSanYuan = default(bool);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"DaSanYuan", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool DaSanYuan
    {
      get { return _DaSanYuan; }
      set { _DaSanYuan = value; }
    }
    private bool _XiaoSanYuan = default(bool);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"XiaoSanYuan", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool XiaoSanYuan
    {
      get { return _XiaoSanYuan; }
      set { _XiaoSanYuan = value; }
    }
    private bool _GangShangKaiHua = default(bool);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"GangShangKaiHua", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool GangShangKaiHua
    {
      get { return _GangShangKaiHua; }
      set { _GangShangKaiHua = value; }
    }
    private bool _GangShangPao = default(bool);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"GangShangPao", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool GangShangPao
    {
      get { return _GangShangPao; }
      set { _GangShangPao = value; }
    }
    private uint _QiangGangHu = default(uint);
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"QiangGangHu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint QiangGangHu
    {
      get { return _QiangGangHu; }
      set { _QiangGangHu = value; }
    }
    private bool _QingYiSe = default(bool);
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"QingYiSe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool QingYiSe
    {
      get { return _QingYiSe; }
      set { _QingYiSe = value; }
    }
    private bool _ShouZhuaYi = default(bool);
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"ShouZhuaYi", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool ShouZhuaYi
    {
      get { return _ShouZhuaYi; }
      set { _ShouZhuaYi = value; }
    }
    private bool _LiangDao = default(bool);
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"LiangDao", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool LiangDao
    {
      get { return _LiangDao; }
      set { _LiangDao = value; }
    }
    private bool _KaWuXing = default(bool);
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"KaWuXing", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool KaWuXing
    {
      get { return _KaWuXing; }
      set { _KaWuXing = value; }
    }
    private bool _BaoHu = default(bool);
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"BaoHu", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool BaoHu
    {
      get { return _BaoHu; }
      set { _BaoHu = value; }
    }
    private bool _SanLongQiDui = default(bool);
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"SanLongQiDui", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool SanLongQiDui
    {
      get { return _SanLongQiDui; }
      set { _SanLongQiDui = value; }
    }
    private bool _LiangDaoFangChong = default(bool);
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"LiangDaoFangChong", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool LiangDaoFangChong
    {
      get { return _LiangDaoFangChong; }
      set { _LiangDaoFangChong = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TING")]
  public partial class TING : global::ProtoBuf.IExtensible
  {
    public TING() {}
    
    private int _ChuPai = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ChuPai", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ChuPai
    {
      get { return _ChuPai; }
      set { _ChuPai = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _TingPai = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"TingPai", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> TingPai
    {
      get { return _TingPai; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LIANG")]
  public partial class LIANG : global::ProtoBuf.IExtensible
  {
    public LIANG() {}
    
    private readonly global::System.Collections.Generic.List<int> _Pai = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Pai", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> Pai
    {
      get { return _Pai; }
    }
  
    private readonly global::System.Collections.Generic.List<TING> _KeChu = new global::System.Collections.Generic.List<TING>();
    [global::ProtoBuf.ProtoMember(2, Name=@"KeChu", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TING> KeChu
    {
      get { return _KeChu; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GAME_STATE")]
  public partial class GAME_STATE : global::ProtoBuf.IExtensible
  {
    public GAME_STATE() {}
    
    private readonly global::System.Collections.Generic.List<PLAYER_STATE> _Player = new global::System.Collections.Generic.List<PLAYER_STATE>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PLAYER_STATE> Player
    {
      get { return _Player; }
    }
  
    private uint _DunCount = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"DunCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint DunCount
    {
      get { return _DunCount; }
      set { _DunCount = value; }
    }
    private uint _DunStart = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"DunStart", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint DunStart
    {
      get { return _DunStart; }
      set { _DunStart = value; }
    }
    private uint _TotalCount = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"TotalCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TotalCount
    {
      get { return _TotalCount; }
      set { _TotalCount = value; }
    }
    private uint _Dice1 = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Dice1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Dice1
    {
      get { return _Dice1; }
      set { _Dice1 = value; }
    }
    private uint _Dice2 = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Dice2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Dice2
    {
      get { return _Dice2; }
      set { _Dice2 = value; }
    }
    private uint _ZhuangJia = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"ZhuangJia", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ZhuangJia
    {
      get { return _ZhuangJia; }
      set { _ZhuangJia = value; }
    }
    private uint _CurPlayer = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"CurPlayer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint CurPlayer
    {
      get { return _CurPlayer; }
      set { _CurPlayer = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _KeChi = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(9, Name=@"KeChi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> KeChi
    {
      get { return _KeChi; }
    }
  
    private bool _KePeng = default(bool);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"KePeng", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool KePeng
    {
      get { return _KePeng; }
      set { _KePeng = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _KeGang = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(11, Name=@"KeGang", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> KeGang
    {
      get { return _KeGang; }
    }
  
    private bool _KeHu = default(bool);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"KeHu", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool KeHu
    {
      get { return _KeHu; }
      set { _KeHu = value; }
    }
    private readonly global::System.Collections.Generic.List<LIANG> _KeLiang = new global::System.Collections.Generic.List<LIANG>();
    [global::ProtoBuf.ProtoMember(13, Name=@"KeLiang", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<LIANG> KeLiang
    {
      get { return _KeLiang; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _BuLiang = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(14, Name=@"BuLiang", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> BuLiang
    {
      get { return _BuLiang; }
    }
  
    private uint _CurRound = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"CurRound", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint CurRound
    {
      get { return _CurRound; }
      set { _CurRound = value; }
    }
    private int _Result = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private int _HuPai = default(int);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"HuPai", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int HuPai
    {
      get { return _HuPai; }
      set { _HuPai = value; }
    }
    private int _DianPao = default(int);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"DianPao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int DianPao
    {
      get { return _DianPao; }
      set { _DianPao = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}